uri_shortner_qr_gen_custom_URL/app/urls.py
from django.contrib import admin
from django.urls import path,include
from . import views


app_name = 'app'

urlpatterns = [
    path('', views.index, name='index'),
    path('site/shorturl/', views.shorturl, name='shorturl'),
    path('<str:short_url>/', views.redirect_original, name='redirect_original'),
    path('qr/qrcode/', views.generate_qr, name='qrcode'),
    path('site/custom_url/', views.customurl, name='customurl'),
    path('c/<str:customurl>/', views.redirect_custom_to_original, name='custom_original'),
    path('site/about/', views.about, name='about'),
    path('site/policy/', views.privacy, name='policy'),
]

uri_shortner_qr_gen_custom_URL/project/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('site/admin/', admin.site.urls),
    path('', include('app.urls')),
]+static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

uri_shortner_qr_gen_custom_URL/app/models.py
from django.db import models

# Create your models here.
from django.db import models

class URL(models.Model):
    original_url = models.URLField()
    short_url = models.CharField(max_length=50, unique=True)
    created_at = models.DateTimeField(auto_now_add=True)
    

    def __str__(self):
        return self.original_url

class Custom_url(models.Model):
    original_url =models.URLField()
    custom_url=models.CharField(max_length=100)
    created=models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.original_url

uri_shortner_qr_gen_custom_URL/app/views.py
# Create your views here.
from django.shortcuts import render, redirect
from django.http import HttpResponse
from .models import URL,Custom_url
import string
import random
import qrcode
from io import BytesIO
from django.core.files import File
from django.conf import settings
import re


def index(request):
    return render(request, 'index.html')

#url shortner
def generate_short_url():
    letters = string.ascii_letters + string.digits + string.ascii_letters + string.digits + string.ascii_letters 
    while True:
        short_url = ''.join(random.choice(letters) for i in range(random.randrange(6,9)))
        if not URL.objects.filter(short_url=short_url).exists():
            return short_url

def shorturl(request):
    if request.method == 'POST':
        original_url = request.POST['original_url']
        short_url = generate_short_url()
        url = URL(original_url=original_url, short_url=short_url)
        url.save()
        short_url = request.build_absolute_uri('/') + short_url
        return render(request, 'shortener/shortened.html', {'short_url': short_url})
    return render(request, 'shortener/shorturl.html')

def redirect_original(request, short_url):
    try:
        url = URL.objects.get(short_url=short_url)
        return redirect(url.original_url)
    except URL.DoesNotExist:
        return HttpResponse('Invalid URL')


#####custom url create
def customurl(request):
    if request.method == 'POST':
        original_url=request.POST['ori_url']
        cus_slug=request.POST['cus_slug']
        if re.search(r"^[\w-]*$", cus_slug):
            if  Custom_url.objects.filter(custom_url=cus_slug).exists():
                used=cus_slug
                return render(request,'custom/custom.html',{'used':used})
            url=Custom_url(original_url=original_url,custom_url=cus_slug)
            url.save()
            customurl= request.build_absolute_uri('/') +'c/'+ cus_slug
            return render(request,'custom/customurl.html',{'custom_url':customurl})
        else:
            slug=cus_slug
            return render(request,'custom/custom.html',{'slug':slug})
    return render(request,'custom/custom.html')

def redirect_custom_to_original(request,customurl):
    try:
        url = Custom_url.objects.get(custom_url=customurl)
        return redirect(url.original_url)
    except Custom_url.DoesNotExist:
        return HttpResponse("<h1>Invalid Url</h1>")




#qr code generator
def generate_qr(request):
    if request.method == 'POST':
        content = request.POST.get('content')
        qr = qrcode.QRCode(version=1, box_size=10, border=5)
        qr.add_data(content)
        qr.make(fit=True)
        img = qr.make_image(fill='black', back_color='white')
        letter = string.ascii_letters 
        name_qr = ''.join(random.choice(letter) for i in range(random.randrange(5,12)))
        file_name = f'qr_code_{name_qr}.png'
        
        file_path = f'{settings.MEDIA_ROOT}/qr/{file_name}'
        print(file_path)
        with open(file_path, 'wb') as f:
            img.save(f, 'PNG') 
        # this is the URL path for browser
        image_url = settings.MEDIA_URL + "qr/" + file_name
        print(image_url)     
        return render(request, 'qrcode/qrcode.html', {'qr_code':file_path,
                                                      'file_name':file_name,
                                                      'file_path':image_url,
                                                      })
    return render(request, 'qrcode/qrcode.html')

def about(request):
    return render(request,'about.html')

def privacy(request):
    return render(request,'policy.html')

def test(request):
    return HttpResponse("<h1>Test is successful</h1>")

uri_shortner_qr_gen_custom_URL/app/templates/about.html
{% extends 'index.html' %}

{% load static %}

{% block style %}
<title> Ihvtool : About  </title>
<meta name="description" content="Ihvtool : This is our about page" />
{% endblock %}

{% block index %}
{% endblock %}

{% block content %}

<div class="container text-center">
    <div class="row">
      <div class="col-lg-6">
        <section class=" text-center container">
          <div class="row py-lg-5">
            <div class="col-lg-8  mx-auto"><b>
              <h1 class="fw-light">It's Your Platform</h1>
            </b>
              <p class="lead ">Our platform allows anyone to shorten any link and generate any url or text into QR code. Sorry, we forgot to mention that our platform is <b>completely free!</b></p>
              <p>
              </p>
            </div>
          </div>
        </section>
      </div>
      <div class="col-lg-6 ">
        <ul class="list-group my-5 ">
            <li class="list-group-item">Url Shortener</li>
            <li class="list-group-item">QR Code Generator</li>
            <li class="list-group-item">Custom URL Generator</li>
          </ul>
      </div>
    </div>
  </div>

  <div class="container">
    <h1 class="text-center mx-2 my2">URL SHORTENER</h1>
    <ul class="list-group my-2">
        <li class="list-group-item list-group-item-primary" aria-disabled="true">How URL Shortner Works?</li>
        <li class="list-group-item">Put Original Url or Link</li>
        <li class="list-group-item">Then Submit Your Url </li>
        <li class="list-group-item">Short Url Has Been Generated</li>
        <li class="list-group-item">Save Your Short URL</li>
    </ul>
    <h1 class="text-center mx-2 my2">QR CODE GENERATOR</h1>
    <ul class="list-group my-2">
        <li class="list-group-item list-group-item-primary" aria-disabled="true">How QR Generator Works?</li>
        <li class="list-group-item">Put any Text, Url or Link</li>
        <li class="list-group-item">Then Click On Generate QR </li>
        <li class="list-group-item">After Generated Download It</li>
        <li class="list-group-item">Save Your QR Code </li>
    </ul>
    <h1 class="text-center mx-2 my2">CUSTOM URL GENERATOR</h1>
    <ul class="list-group my-2">
        <li class="list-group-item list-group-item-primary" aria-disabled="true">How Custom Url Works?</li>
        <li class="list-group-item">Put Original Url or Link</li>
        <li class="list-group-item">Put your custom url name </li>
        <li class="list-group-item">You can use only alphabet,numbers & '-'</li>
        <li class="list-group-item">Example (valid) : Blearningclub-8-new </li>
        <li class="list-group-item">Example (not valid): Blearning/new/8%abc</li>
        <li class="list-group-item">Save your custom url & then exit </li>
    </ul>
  </div>
{% endblock %}

uri_shortner_qr_gen_custom_URL/app/templates/custom/custom.html
{% extends 'index.html' %}

{% load static %}

{% block style %}
<title>Custom URL at your Fingertips </title>
<meta name="description" content="Our Custom URL Generator is one of the fastest and free tools available on the internet. Check it out and design your own custom URL." />
<style>


    /* Style 9
       ----------------------------- */
       .nine h1 {
      text-align:center; font-size:50px; text-transform:uppercase; color:#222; letter-spacing:1px;
      font-family:"Playfair Display", serif; font-weight:400;
    }
 .para p {
    text-align:center; font-size:20px; text-transform:uppercase; color:#222; letter-spacing:1px;
      font-family:"Playfair Display", serif; font-weight:100;

 }
    
    
    </style>
{% endblock %}

{% block index %}
{% endblock %}



{% block content %}
<div class="container">
    <div class="row">
        <div class="col">
            <div class="nine">
                <h1>Custom Url</h1>
               
              </div>
              <div class="para">
                <p class="text-center"> Free & Fastest custom url Generator on the planet</p>
              </div>
            <form method="POST" action=".">
                {% csrf_token %}
                <div class="mb-3">
                  <label for="original_url" class="form-label">Put Original URL:</label>
                  <input type="url" class="form-control" name="ori_url" required>
                  <label for="original_url" class="form-label">Put custom name :</label>
                  <input type="text" class="form-control" name="cus_slug" required>
                  <div  class="form-text">We'll never share your url and custom url</div>
                </div>
                <button type="submit"  class="btn btn-lg btn-primary">Submit</button>
            </form>
            {% if used %}
            <p class="text-center bg-success-subtle mx-2 my-2 p-3">Your custom url <b>{{used}}</b> has been already used. Please try other.</p>
            {% endif %}
            {% if slug %}
            <p class="text-center bg-success-subtle mx-2 my-2 p-3">Your custom url <b>{{slug}}</b> is not Valid . please use alphanumeric or '-'</p> 
            {% endif %}
        </div>
    </div>


    <div class="row my-2">
        <div class="col-lg-6">
            <img src="{% static 'pic/custom2.png' %}" height="400" width="300" class="text-center bd-placeholder-img mx-auto" alt="...">
        </div>
        <div class="col-lg-6">
            <ul class="list-group ">
                <li class="list-group-item list-group-item-primary" aria-disabled="true">How Custom Url Works?</li>
                <li class="list-group-item">Put Original Url or Link</li>
                <li class="list-group-item">Put your custom url name </li>
                <li class="list-group-item">You can use only alphabet,numbers & '-'</li>
                <li class="list-group-item">Example (valid) : Blearningclub-8-new </li>
                <li class="list-group-item">Example (not valid): Blearning/new/8%abc</li>
                <li class="list-group-item">Save your custom url & then exit </li>
              </ul>
        </div>
    </div>
    
</div>
{% endblock %}

uri_shortner_qr_gen_custom_URL/app/templates/custom/customurl.html
{% extends 'index.html' %}
{% load static %}


{% block style %}
<title>Ihvtool: Custom Url  </title>
<meta name="description" content="Our Custom URL Generator is one of the fastest and free tools available on the internet. Check it out and design your own custom URL." />
<style>


/* Style 9
   ----------------------------- */
.nine h1 {
  text-align:center; font-size:50px; text-transform:uppercase; color:#222; letter-spacing:1px;
  font-family:"Playfair Display", serif; font-weight:400;
}
.nine h1 span {
  margin-top: 5px;
    font-size:15px; color:#444; word-spacing:1px; font-weight:normal; letter-spacing:2px;
    text-transform: uppercase; font-family:"Raleway", sans-serif; font-weight:500;

    display: grid;
    grid-template-columns: 1fr max-content 1fr;
    grid-template-rows: 27px 0;
    grid-gap: 20px;
    align-items: center;
}

.nine h1 span:after,.nine h1 span:before {
    content: " ";
    display: block;
    border-bottom: 1px solid #ccc;
    border-top: 1px solid #ccc;
    height: 5px;
  background-color:#f8f8f8;
}


</style>
{% endblock %}





{% block index %}
{% endblock %}


{% block content %}
<div class="container">
  <div class="nine">
    <h1>CUSTOMED URL<span>
        SAVE THIS URL</span></h1>
  </div>
    
    <form>
        <div class="mb-3">
          <label for="exampleInputEmail1" class="form-label">Your CUSTOM URL</label>
          <input id="myInput" value="{{ custom_url }}" class="form-control"  aria-describedby="emailHelp">
         
        </div>

    <p class="text-center px-2 py-2 text-primary-emphasis bg-primary-subtle border border-primary-subtle rounded-3" id="my_url">Your Custom URL is <b>{{ custom_url }}</b> please copy it and store it   </p>
    <button onclick="myFunction()" type="button" class="btn btn-primary btn-lg">COPY URL</button>
    <div class="row my-2">
      <div class="col-lg-6">
          <img src="{% static 'pic/custom2.png' %}" height="400" width="300" class="text-center bd-placeholder-img mx-auto" alt="...">
      </div>
      <div class="col-lg-6">
          <ul class="list-group ">
              <li class="list-group-item list-group-item-primary" aria-disabled="true">How Custom Url Works?</li>
              <li class="list-group-item">Put Original Url or Link</li>
              <li class="list-group-item">Put your custom url name </li>
              <li class="list-group-item">You can use only alphabet,numbers & '-'</li>
              <li class="list-group-item">Example (valid) : Blearningclub-8-new </li>
              <li class="list-group-item">Example (not valid): Blearning/new/8%abc</li>
              <li class="list-group-item">Save your custom url & then exit </li>
            </ul>
      </div>
  </div>
</div>

<script>
    function myFunction() {
      // Get the text field
      var copyText = document.getElementById("myInput");
    
      // Select the text field
      copyText.select();
      copyText.setSelectionRange(0, 99999); // For mobile devices
    
      // Copy the text inside the text field
      navigator.clipboard.writeText(copyText.value);
      
      // Alert the copied text
      alert("Copied the text: " + copyText.value);
    }
</script>


{% endblock %}

uri_shortner_qr_gen_custom_URL/app/templates/index.html
<!doctype html>
{% load static %}
<html lang="en">
  <head>
    <link rel="icon" type="image/x-icon" href="{% static 'favic.png' %}">
    {% block style %}
    <title>Ihvtool: Free Web Tools</title>
    <meta name="description" content="Ihvtool is one of the best web tool websites available on the planet. In addition, it is totally free to use. Let's jump into our website and use our QR Code generator, URL Shortner, and Custom URL Generator" />
    {% endblock %}


    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
   
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
  </head>
  <body>


    <nav class="navbar navbar-expand-lg bg-body-tertiary  " style="background-color:#ffffff    !important;">
      <div class="container-fluid">
        <a class="navbar-brand text-primary" href="#">
          <img src="{% static 'icons.png' %}" alt="Bootstrap" width="100" height="50"></a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarScroll" aria-controls="navbarScroll" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarScroll">
          <ul class="navbar-nav me-auto my-2 my-lg-0 navbar-nav-scroll" style="--bs-scroll-height: 100px;">
            <li class="nav-item"><b>
              <a class="nav-link active text-primary" aria-current="page" href="{% url 'app:index' %}">Home</a>
            </b>
            </li>
            <li class="nav-item">
             <b>
              <a class="nav-link text-primary" href="{% url 'app:qrcode' %}">Qr Generator</a>
             </b> 
            </li>
            <li class="nav-item">
              <b>
               <a class="nav-link text-primary" href="{% url 'app:shorturl' %}">URL Shortener</a>
              </b> 
            </li>  
            <li class="nav-item">
              <b>
               <a class="nav-link text-primary" href="{% url 'app:customurl' %}">Custom Url</a>
              </b> 
            </li>  
            <li class="nav-item">
              <b>
               <a class="nav-link text-primary" href="{% url 'app:about' %}">About</a>
              </b> 
            </li>         
          </ul>
        </div>
      </div>
    </nav>



{% block index %}
    <div class="container text-center">
      <div class="row">
        <div class="col">
          <section class="py-5 text-center container">
            <div class="row py-lg-5">
              <div class="col-lg-8  mx-auto"><b>
                <h1 class="fw-light">It's Your Platform</h1>
              </b>
                <p class="lead ">Our platform allows anyone to shorten any link and generate any url or text into QR code and generate your custom url. Sorry, we forgot to mention that our platform is <b>completely free!</b></p>
                <p>
                  <a href="{% url 'app:qrcode' %}" class="btn  btn-outline-success my-2  ">Qr Generator</a>
                  <a href="{% url 'app:shorturl' %}" class="btn  btn-outline-success my-2  ">Url Shortener</a>
                  <a href="{% url 'app:customurl' %}" class="btn  btn-outline-success my-2  ">Custom Url</a>
                </p>
              </div>
            </div>
          </section>
        </div>
        <div class="col">
          <img src="{% static 'pic/frontimg.png' %}" height="400" width="300" class="rounded mx-auto d-block" alt="...">
        </div>
      </div>
    </div>

<div class="container">
  <div class="row mb-2">
    <div class="col-md-6">
      <div class="row g-0 border rounded overflow-hidden flex-md-row mb-4 shadow-md h-md-250 position-relative">
        <div class="col p-4 d-flex flex-column position-static">
          <strong class="d-inline-block mb-2 text-primary">URL Shortener</strong>
          <h3 class="mb-0">URl Shortener</h3>
          <p class="card-text mb-auto">This is Url shortener. You can type any url and we will generate short url for you. Please save your short url after generating. </p>
          <a href="{% url 'app:shorturl' %}" class="btn btn-success ">URL SHORTENER</a>
        </div>
        <div class="col-auto d-none d-lg-block">
          <img src="{% static 'pic/urlcard.png' %}" height="250" width="200" class=" bd-placeholder-img mx-auto" alt="...">
        
        </div>
      </div>
    </div>
    <div class="col-md-6">
      <div class="row g-0 border rounded overflow-hidden flex-md-row mb-4 shadow-md h-md-250 position-relative">
        <div class="col p-4 d-flex flex-column position-static">
          <strong class="d-inline-block mb-2 text-success">QR Code</strong>
          <h3 class="mb-0">Qr Code Generator</h3>
          <p class="mb-auto">Here you can generate Qr code of any link and Text. It is absolutely free of cost. Please Download your QR code.</p>
          <a href="{% url 'app:qrcode' %}" class="btn btn-success">QR CODE GENERATOR</a>
        </div>
        <div class="col-auto d-none d-lg-block">
          <img src="{% static 'pic/qrcode.png' %}" height="250" width="200" class=" bd-placeholder-img mx-auto" alt="...">
        </div>
      </div>
    </div>
  </div>
</div>

<div class="container">
  <div class="row mb-2">
    <div class="col-md-6">
      <div class="row g-0 border rounded overflow-hidden flex-md-row mb-4 shadow-md h-md-250 position-relative">
        <div class="col p-4 d-flex flex-column position-static">
          <strong class="d-inline-block mb-2 text-primary">Custom URL</strong>
          <h3 class="mb-0">Custom Url</h3>
          <p class="card-text mb-auto">Create your custom url easily. You can choose the custom url of any Link. It's absolutely free and Easy. </p>
          <a href="{% url 'app:customurl' %}" class="btn btn-success ">Custom Url</a>
        </div>
        <div class="col-auto d-none d-lg-block">
          <img src="{% static 'pic/custom1.png' %}" height="250" width="200" class=" bd-placeholder-img mx-auto" alt="...">
        
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}


{% block content %}
   
{% endblock %}
<div class="container-fluid">
  <footer class="py-5 bg-body-tertiary "  >

    <p class="mb-0">This website is &copy; Ihvtool, Here you can use our tools absolutely free of cost.</p>
    <p class="mb-0">If you like our website please refers others. We will be very greatful to serve you. <a href="{% url 'app:about' %}">About Us</a></p>
    <p class="mb-0">Have you any query and feedback please email:<a href="mailto:m.bluth@example.com">coffewithbhaskar13@gmail.com</a> & <a href="{% url 'app:policy' %}">Privacy & Policy</a></p>
    <p class="float-end mb-1">
      <a href="#">Back to top</a>
    </p>

  </footer>

</div>


  

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js" integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN" crossorigin="anonymous"></script>
  </body>
</html>

uri_shortner_qr_gen_custom_URL/app/templates/policy.html
{% extends 'index.html' %}

{% load static %}

{% block style %}
<title> Ihvtool : Privacy & Policy </title>
<meta name="description" content="Ihvtool : Privacy & Policy" />
<style>


    /* Style 9
       ----------------------------- */
       .nine h1 {
      text-align:center; font-size:50px; text-transform:uppercase; color:#222; letter-spacing:1px;
      font-family:"Playfair Display", serif; font-weight:400;
    }
    .nine h1 span {
      margin-top: 5px;
        font-size:15px; color:#444; word-spacing:1px; font-weight:normal; letter-spacing:2px;
        text-transform: uppercase; font-family:"Raleway", sans-serif; font-weight:500;
    
        display: grid;
        grid-template-columns: 1fr max-content 1fr;
        grid-template-rows: 27px 0;
        grid-gap: 20px;
        align-items: center;
    }
    
    .nine h1 span:after,.nine h1 span:before {
        content: " ";
        display: block;
        border-bottom: 1px solid #ccc;
        border-top: 1px solid #ccc;
        height: 5px;
      background-color:#f8f8f8;
    }
    
    
    </style>
{% endblock %}

{% block index %}
{% endblock %}

{% block content %}
<div class="nine">
    <h1>PRIVACY & POLICY<span>
       This is our privacy & policy</span></h1>
</div>
  <div class="container my-2">

    <ul class="list-group my-2">
        <li class="list-group-item " >Users are first priority </li>
        <li class="list-group-item">We never share Your Url</li>
        <li class="list-group-item">Your url lasted for 60 days</li>
        <li class="list-group-item">For extend you can contact email at footer</li>
        <li class="list-group-item">Always Save Your Generated URL. We never give you again</li>
        <li class="list-group-item">We never share your QR code</li>
        <li class="list-group-item">Feel free to use our service</li>
        <li class="list-group-item">Any difficulty contact us. Contact details in footer </li>

    </ul>
  </div>
{% endblock %}

uri_shortner_qr_gen_custom_URL/app/templates/qrcode/qrcode.html
{% extends 'index.html' %}


{% load static %}

{% block style %}
<title>QR Code Generator at your Fingertips </title>
<meta name="description" content="Our QR Code Generator is one of the fastest and free tools available on the internet. Check it out and generator anything into a QR Code" />

<style>


/* Style 9
   ----------------------------- */
   .nine h1 {
  text-align:center; font-size:50px; text-transform:uppercase; color:#222; letter-spacing:1px;
  font-family:"Playfair Display", serif; font-weight:400;
}

.para p {
  text-align:center; font-size:20px; text-transform:uppercase; color:#222; letter-spacing:1px;
  font-family:"Playfair Display", serif; font-weight:100;
}

</style>
{% endblock %}



{% block index %}
{% endblock %}


{% block content %}
{% load static %}
<div class="container">
  <div class="nine">
    <h1 class="text-capital">QR Code Generator</h1>
  </div>
  <div class="para">
    <p>
      Perfectly coded QR code generator
    </p>
  </div>
  <div class="row">
    <div class="col-md-6 offset-md-3">

      {% if qr_code %}
      <div class="text-center mt-5">
        <h3 class="text-center mb-5">You Qr Code is here please download it</h3>
        <a class="btn btn-lg btn-success" href="{{file_path}}" download>Download this image!</a>
        <img src="{{file_path}}" alt="QR Code">
      </div>
      {% endif %}
      <form action="." method="POST">
        {% csrf_token %}
        <div class="form-group">
          <label for="content">Content (Type any url or Text)</label>
          <textarea class="form-control mx-2 my-2" id="content" name="content" rows="3" required></textarea>
        </div>
        <button type="submit" class="btn btn-lg btn-primary mx-2 my-2 p-3">Generate QR</button>
      </form>

    </div>

  </div>

  <div class="row my-2">
    <div class="col-lg-6">
        <img src="{% static 'pic/qrcode.png' %}" height="400" width="300" class="text-center bd-placeholder-img mx-auto" alt="...">
    </div>
    <div class="col-lg-6">
        <ul class="list-group ">
            <li class="list-group-item list-group-item-primary" aria-disabled="true">How QR Generator Works?</li>
            <li class="list-group-item">Put any Text, Url or Link</li>
            <li class="list-group-item">Then Click On Generate QR </li>
            <li class="list-group-item">After Generated Download It</li>
            <li class="list-group-item">Save Your QR Code </li>
          </ul>
    </div>
</div>


</div>
{% endblock %}

uri_shortner_qr_gen_custom_URL/app/templates/shortener/shortened.html
{% extends 'index.html' %}
{% load static %}


{% block style %}
<title> URL Shortener  </title>
<meta name="description" content="Our URL Shortener is one of the fastest and free tools available on the internet. Check it out and shorten your URL with just a few clicks" />



<style>


/* Style 9
   ----------------------------- */
   .nine h1 {
  text-align:center; font-size:50px; text-transform:uppercase; color:#222; letter-spacing:1px;
  font-family:"Playfair Display", serif; font-weight:400;
}
.nine h1 span {
  margin-top: 5px;
    font-size:15px; color:#444; word-spacing:1px; font-weight:normal; letter-spacing:2px;
    text-transform: uppercase; font-family:"Raleway", sans-serif; font-weight:500;

    display: grid;
    grid-template-columns: 1fr max-content 1fr;
    grid-template-rows: 27px 0;
    grid-gap: 20px;
    align-items: center;
}

.nine h1 span:after,.nine h1 span:before {
    content: " ";
    display: block;
    border-bottom: 1px solid #ccc;
    border-top: 1px solid #ccc;
    height: 5px;
  background-color:#f8f8f8;
}


</style>
{% endblock %}





{% block index %}
{% endblock %}


{% block content %}
<div class="container">
  <div class="nine">
    <h1>SHORTENED URL<span>
        SAVE THIS URL</span></h1>
  </div>
      
      <form>
          <div class="mb-3">
            <label for="exampleInputEmail1" class="form-label">Your Short URL</label>
            <input id="myInput" value="{{ short_url }}" class="form-control"  aria-describedby="emailHelp">
          
          </div>

      <p class="text-center px-2 py-2 text-primary-emphasis bg-primary-subtle border border-primary-subtle rounded-3" id="my_url">Your short url is <b>{{ short_url }}</b> please copy it and store it   </p>
      <button onclick="myFunction()" type="button" class="btn btn-primary btn-lg">COPY URL</button>

      <div class="row my-2">
        <div class="col-lg-6">
            <img src="{% static 'pic/urlcard.png' %}" height="400" width="300" class="text-center bd-placeholder-img mx-auto" alt="...">
        </div>
        <div class="col-lg-6">
            <ul class="list-group ">
                <li class="list-group-item list-group-item-primary" aria-disabled="true">How URL Shortener Works?</li>
                <li class="list-group-item">Put Original Url or Link</li>
                <li class="list-group-item">Then Submit Your Url </li>
                <li class="list-group-item">Short Url Has Been Generated</li>
                <li class="list-group-item">Save Your Short URL</li>
              </ul>
        </div>
      </div>
</div>

<script>
    function myFunction() {
      // Get the text field
      var copyText = document.getElementById("myInput");
    
      // Select the text field
      copyText.select();
      copyText.setSelectionRange(0, 99999); // For mobile devices
    
      // Copy the text inside the text field
      navigator.clipboard.writeText(copyText.value);
      
      // Alert the copied text
      alert("Copied the text: " + copyText.value);
    }
</script>


{% endblock %}